import RecoilContextProvider from "./recoilContextProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
  title: "joa-openapi",
  description: "Generated by Next.js",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body id={"root"}>
      <img src='Banner.png' className='absolute top-0 right-0 w-[48rem] -z-10 opacity-70' />
        <RecoilContextProvider>
          <Header />
          {children}
          <Footer />
        </RecoilContextProvider>
      </body>
    </html>
  );
}




