import RecoilContextProvider from "./recoilContextProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Noto_Sans_KR } from 'next/font/google';

export const metadata = {
  title: "joa-openapi",
  description: "Generated by Next.js",
};

const noto = Noto_Sans_KR({
  subsets: ['latin'], // 또는 preload: false
});

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body id={"root"} className={noto.className}>
      <img src='Banner.png' className='absolute top-0 right-0 w-[48rem] -z-10 opacity-70' />
        <RecoilContextProvider>
          <Header />
          {children}
          <Footer />
        </RecoilContextProvider>
      </body>
    </html>
  );
}




