import RecoilContextProvider from "./recoilContextProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";


export const metadata = {
  title: "joa-openapi",
  description: "Generated by Next.js",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body id={"root"}>
        <RecoilContextProvider>
          <Header />
          {children}
          <Footer />
        </RecoilContextProvider>
      </body>
    </html>
  );
}


